### ISSUE TITLE
V. 4.12.0 duplicate symbols for x86_64 

### ISSUE THREAD

**Issue by bladebunny** [ooyala/ios-sdk-podspecs#12]
I just pulled down the latest update via Cocoapods and immediately got a duplicate symbols issue in my build.  Downgrading back to 4.11.0 worked fine.  Looks like a multiple import problem in the project.

Symbol dups:
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._height in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._offset in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._viewTrackings in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._clickTrackings in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._yPosition in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._xPosition in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._duration in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_CLASS_$_OOVASTIcon in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_METACLASS_$_OOVASTIcon in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._program in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._resourceUrl in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._apiFramework in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._width in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._clickThrough in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._type in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
duplicate symbol _OBJC_IVAR_$_OOVASTIcon._creativeType in:
    /Users/tibrook/Documents/Source/flagship-ios/Pods/OoyalaSDK/vendor/Ooyala/OoyalaSDK-iOS/OoyalaSDK.framework/OoyalaSDK(OOVASTIcon-44ED8FF19C67A197.o)
ld: 16 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by dwnld-mitch** [comment]
Seeing this same issue.

**Comment by jonslenkooyala** [comment]
Thank you for the reports. We'll look into it asap.

**Comment by lental** [comment]
Have you guys tried the PlaybackLab/CocoaPodsSampleApp?  I was able to set the PodFile to 4.12.0, pod install, then  compile/run the app on Simulator and Device successfully.

**Comment by cquintanaMegaMedia** [comment]
Hello i have exactly same issue.

**Comment by liviur** [comment]
Same here
4.11.0 - all is good , later versions run into this issue

**Comment by lental** [comment]
Have you tried the PlaybackLab/CocoaPodsSampleApp? I was able to set the PodFile to 4.12.0, pod install, then compile/run the app on Simulator and Device successfully.  I haven't tried latest ones personally, but i'll try that today

**Comment by liviur** [comment]
@lental The PlaybackLab/CocoaPodsSampleApp currently still has sdk 4.5.0 , when trying to remove the version lock and run pod update the following happens:
```
pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing OoyalaSDK 4.17.0 (was 4.5.0)

[!] Error installing OoyalaSDK
[!] /usr/local/bin/git clone https://github.com/ooyala/ios-sample-apps.git /var/folders/t1/z96d6ssd0kn7tyscbbk7h2n80000gn/T/d20160824-58129-zt1f9i --template= --single-branch --depth 1 --branch v4.17.0

Cloning into '/var/folders/t1/z96d6ssd0kn7tyscbbk7h2n80000gn/T/d20160824-58129-zt1f9i'...
warning: Could not find remote branch v4.17.0 to clone.
fatal: Remote branch v4.17.0 not found in upstream origin
```

As a side note - since we have it more narrowed down - when adding a private pod we have it introduces the problem so I'll try to add the delta we are doing at the pod spec level in case it might help.

**Comment by liviur** [comment]
config additions:
```
s.xcconfig = { 'CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES' => 'YES',
								 'OTHER_LDFLAGS' => '$(inherited) -objc -all_load,
								 	'ENABLE_BITCODE' => 'NO',
									'GCC_WARN_UNDECLARED_SELECTOR' => "NO",
									'FRAMEWORK_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}"/**',
									'LIBRARY_SEARCH_PATHS' => '$(inherited) "${PODS_ROOT}"/**'
								}
```

This happens even when importing the framework directly

**Comment by liviur** [comment]
OK :) got it.
Problem is when usual `-all_load`

So whoever uses pods with `-all_load` or has it in his project will encounter it.

**Comment by lental** [comment]
oy, the infamous linker flags..  Good find though.

by the way, I saw the 4.17.0 podspecs were bad, so i fixed those too :)

**Comment by liviur** [comment]
cool , for whoever still encounters the bad pod specs - note you need `pod update` or `pod repo update` and than it will install the updated versions.

**Comment by cquintanaMegaMedia** [comment]
Thanks Liviur!

**Comment by S0MMS** [comment]
I'm running into this as well.  Have done pod repo update...still a problem migrating from 4.11 to 4.12...getting the 'duplicate symbol' error.  Is the fix to remove '-all_load' from Other Linker Flags setting?  Will this adversely affect my other Pods?

**Comment by lental** [comment]
@S0MMS  I can't say for certain, of course, because each app is different.  I've historically seen most third parties suggest using -ObjC linker flag.  if you have issues removing -all_load, consider setting -ObjC and see if that helps
